export const attorneys = [
  {
    slug: "hanumanta-rao",
    initials: "HR",
    name: "Adv. Hanumanta Rao",
    designation: "Senior Counsel",
    enrollment: "Bar Council of Telangana · Enrl. No. TG/0001/1998",
    avatarBg: "#1A3A6B",
    specialisation: "Constitutional Law & Public Interest Litigation",
    practiceAreas: ["constitutional-law", "civil-litigation", "criminal-defence"],
    experience: "25+ years",
    education: [
      "LL.B. — Osmania University, Hyderabad (1997)",
      "Post-Graduate Diploma in Constitutional Law — NALSAR University of Law",
    ],
    courts: ["Supreme Court of India", "Telangana High Court", "Andhra Pradesh High Court", "NCLT Hyderabad Bench"],
    bio: "Adv. Hanumanta Rao is one of Hyderabad's foremost constitutional advocates, with over 25 years of dedicated practice at the Telangana High Court and frequent appearances before the Supreme Court of India. A former Additional Advocate General of Telangana, he has argued over 150 writ petitions and PILs — many setting binding precedents on fundamental rights, administrative law, and state power. His advocacy is marked by meticulous preparation, a deep command of constitutional doctrine, and a steadfast commitment to the rule of law. Outside the courtroom, he mentors junior advocates and contributes regularly to bar council publications on constitutional jurisprudence.",
    highlights: [
      "Former Additional Advocate General, Government of Telangana",
      "150+ Writ Petitions & PILs successfully argued",
      "Senior Advocate designation — Supreme Court of India",
      "Led arguments in landmark Telangana High Court constitutional bench matters",
      "Represented state corporations and private parties in high-profile administrative law cases",
    ],
    notableMatters: [
      {
        title: "State of Telangana vs. Rao Corporation",
        outcome: "Favorable ruling — Supreme Court",
        description: "Successfully challenged the constitutional validity of a state tax amendment, setting a nationwide precedent on the limits of state taxation power.",
      },
      {
        title: "PIL — Right to Clean Air, Musi River",
        outcome: "High Court directions issued",
        description: "Filed and argued a landmark PIL resulting in binding directions to GHMC and pollution control authorities on industrial discharge into the Musi river.",
      },
      {
        title: "Government Employee Reinstatement Matter",
        outcome: "Full reinstatement ordered",
        description: "Secured reinstatement with full back-pay for a senior government officer dismissed without following due process under Article 311 of the Constitution.",
      },
    ],
    metaTitle: "Adv. Hanumanta Rao — Senior Counsel | Constitutional Law | Sharma & Associates",
    metaDescription:
      "Profile of Adv. Hanumanta Rao, Senior Counsel at Sharma & Associates, Hyderabad. Former Additional Advocate General, Telangana. Expert in constitutional law and PILs.",
  },
  {
    slug: "ramarao",
    initials: "RR",
    name: "Adv. Ramarao",
    designation: "Senior Counsel",
    enrollment: "Bar Council of Telangana · Enrl. No. TG/0047/2001",
    avatarBg: "#2d3748",
    specialisation: "Criminal Defence & Financial Crimes",
    practiceAreas: ["criminal-defence", "civil-litigation"],
    experience: "22+ years",
    education: [
      "LL.B. — Kakatiya University, Warangal (2000)",
      "Certificate in Forensic Evidence & Criminal Investigation — NLSIU Bangalore",
    ],
    courts: ["Supreme Court of India", "Telangana High Court", "CBI Special Court", "PMLA Special Court, Hyderabad"],
    bio: "Adv. Ramarao commands 22 years of experience in criminal trial advocacy, anticipatory bail jurisprudence, and the defence of complex PMLA and economic offence cases. Known across the Telangana bar for his incisive cross-examinations, thorough command of forensic evidence, and ability to identify procedural infirmities in prosecution filings, he has secured acquittals and bail relief in some of Hyderabad's most high-profile criminal matters. He maintains an unwavering commitment to client confidentiality and is available for urgent bail matters at short notice.",
    highlights: [
      "22+ years in criminal trial advocacy at trial courts and Telangana High Court",
      "PMLA, NDPS, and economic offence specialist",
      "100+ bail and anticipatory bail applications — High Court and Supreme Court",
      "Successfully argued FIR quashing petitions in dozens of matters",
      "Defence counsel in multiple multi-crore financial fraud trials",
    ],
    notableMatters: [
      {
        title: "In re: Cyberabad Financial Fraud Case",
        outcome: "Full acquittal — Sessions Court",
        description: "Defended key executives in a multi-crore alleged financial fraud. Demonstrated procedural defects in the chargesheet and gaps in prosecution evidence, resulting in complete exoneration.",
      },
      {
        title: "PMLA Bail — Prominent Hyderabad Businessman",
        outcome: "Bail granted — Telangana High Court",
        description: "Secured bail for a senior businessman in a complex money laundering matter by successfully challenging the statutory presumption under PMLA Section 45.",
      },
      {
        title: "Anticipatory Bail — Senior Civil Servant",
        outcome: "Anticipatory bail granted",
        description: "Obtained anticipatory bail for a senior IAS officer facing allegations in a disproportionate assets matter, protecting them from arrest pending investigation.",
      },
    ],
    metaTitle: "Adv. Ramarao — Senior Counsel | Criminal Defence, PMLA | Sharma & Associates",
    metaDescription:
      "Profile of Adv. Ramarao, Senior Counsel at Sharma & Associates, Hyderabad. Expert in criminal defence, PMLA, anticipatory bail, and economic offences.",
  },
  {
    slug: "priya-sharma",
    initials: "PS",
    name: "Adv. Priya Sharma",
    designation: "Associate",
    enrollment: "Bar Council of Telangana · Enrl. No. TG/1204/2018",
    avatarBg: "#1A3A6B",
    specialisation: "Property & Real Estate Law",
    practiceAreas: ["property-real-estate", "civil-litigation"],
    experience: "6 years",
    education: ["LL.B. — NALSAR University of Law, Hyderabad (2018)"],
    courts: ["Telangana High Court", "City Civil Court Hyderabad", "TSRERA"],
    bio: "Adv. Priya Sharma joined Sharma & Associates after graduating from NALSAR University of Law and has built a focused practice in property law and real estate transactions in the Hyderabad market. She conducts title due diligence, drafts sale and lease documentation, represents clients before the Telangana RERA authority, and handles landlord-tenant disputes before civil courts. She is known for her thorough document review and clear client communication.",
    highlights: [
      "NALSAR University of Law graduate — Silver Medallist",
      "Specialisation in TSRERA filings and builder disputes",
      "50+ property due diligence reports prepared",
    ],
    notableMatters: [
      {
        title: "RERA Builder Delay Compensation",
        outcome: "Full compensation ordered — TSRERA",
        description: "Secured compensation and interest for homebuyers in a delayed residential project in Kondapur, Hyderabad.",
      },
      {
        title: "Landlord Eviction and Rent Recovery",
        outcome: "Eviction and arrears decree",
        description: "Obtained eviction order and recovery of 24 months' arrear rent for a commercial landlord in Banjara Hills.",
      },
      {
        title: "Title Dispute — Ancestral Property",
        outcome: "Injunction granted",
        description: "Secured a stay order preventing illegal sale of disputed ancestral agricultural land pending partition suit.",
      },
    ],
    metaTitle: "Adv. Priya Sharma — Associate | Property & Real Estate Law | Sharma & Associates",
    metaDescription: "Profile of Adv. Priya Sharma, Associate Advocate at Sharma & Associates, Hyderabad. Specialises in property law, TSRERA, and real estate transactions.",
  },
  {
    slug: "kiran-reddy",
    initials: "KR",
    name: "Adv. Kiran Reddy",
    designation: "Associate",
    enrollment: "Bar Council of Telangana · Enrl. No. TG/0998/2019",
    avatarBg: "#1A3A6B",
    specialisation: "Civil Litigation",
    practiceAreas: ["civil-litigation", "corporate-law"],
    experience: "5 years",
    education: ["LL.B. — Osmania University, Hyderabad (2019)"],
    courts: ["Telangana High Court", "City Civil Court Hyderabad", "District Courts"],
    bio: "Adv. Kiran Reddy has developed a strong civil litigation practice since joining the chamber, with a particular focus on injunction proceedings, money recovery suits, and contractual disputes. He has appeared extensively before the City Civil Court Hyderabad and the Telangana High Court and is adept at drafting urgent applications for interim relief.",
    highlights: [
      "Strong track record in obtaining interim injunctions",
      "Experience in NI Act Section 138 cheque dishonour matters",
      "Assisted in high-value commercial arbitration proceedings",
    ],
    notableMatters: [
      {
        title: "Commercial Contract Dispute — IT Sector",
        outcome: "Settlement — significant recovery",
        description: "Represented an IT services company in a contract dispute, securing a favourable out-of-court settlement after filing suit.",
      },
      {
        title: "Section 138 NI Act — Cheque Bounce",
        outcome: "Conviction and compensation",
        description: "Successfully prosecuted a cheque dishonour case resulting in conviction and full compensation for the client.",
      },
    ],
    metaTitle: "Adv. Kiran Reddy — Associate | Civil Litigation | Sharma & Associates",
    metaDescription: "Profile of Adv. Kiran Reddy, Associate Advocate at Sharma & Associates, Hyderabad. Specialises in civil litigation, injunctions, and recovery suits.",
  },
  {
    slug: "meghana-rao",
    initials: "MR",
    name: "Adv. Meghana Rao",
    designation: "Associate",
    enrollment: "Bar Council of Telangana · Enrl. No. TG/1389/2020",
    avatarBg: "#374151",
    specialisation: "Family Law",
    practiceAreas: ["family-law"],
    experience: "4 years",
    education: ["LL.B. — University College of Law, Osmania University (2020)"],
    courts: ["Telangana High Court", "Family Courts — Hyderabad", "District Courts"],
    bio: "Adv. Meghana Rao handles family law matters with exceptional sensitivity and professionalism. She advises and represents clients in divorce proceedings, child custody disputes, maintenance applications, and domestic violence matters. She is committed to client confidentiality and to securing outcomes that protect the interests of children and vulnerable parties.",
    highlights: [
      "Family Court appearances in Hyderabad, Rangareddy, and Medchal",
      "Extensive experience in mutual consent divorce filings",
      "DV Act protection order specialist",
    ],
    notableMatters: [
      {
        title: "Contested Custody — Minor Children",
        outcome: "Sole custody secured",
        description: "Secured sole custody of two minor children for a working mother by demonstrating the father's unfitness and the children's wellbeing.",
      },
      {
        title: "Domestic Violence Protection Order",
        outcome: "Urgent protection order granted",
        description: "Obtained an emergency protection order for a survivor of domestic violence within 48 hours of filing.",
      },
    ],
    metaTitle: "Adv. Meghana Rao — Associate | Family Law | Sharma & Associates",
    metaDescription: "Profile of Adv. Meghana Rao, Associate Advocate at Sharma & Associates, Hyderabad. Specialises in family law, divorce, child custody, and domestic violence matters.",
  },
  {
    slug: "suresh-kumar",
    initials: "SK",
    name: "Adv. Suresh Kumar",
    designation: "Associate",
    enrollment: "Bar Council of Telangana · Enrl. No. TG/0812/2017",
    avatarBg: "#122B52",
    specialisation: "Corporate Law",
    practiceAreas: ["corporate-law", "civil-litigation"],
    experience: "7 years",
    education: [
      "LL.B. — NALSAR University of Law, Hyderabad (2017)",
      "Post-Graduate Certificate in Corporate Governance",
    ],
    courts: ["NCLT Hyderabad Bench", "Telangana High Court", "City Civil Court"],
    bio: "Adv. Suresh Kumar is the most senior of our associates with seven years of corporate law practice. He assists businesses in Hyderabad's Hitech City and GACHIBOWLI corridors with incorporation, compliance, shareholder documentation, and NCLT proceedings. He advises startups, MSMEs, and listed companies on regulatory obligations and corporate governance.",
    highlights: [
      "7 years of corporate practice — Hyderabad",
      "Assisted in 20+ company incorporations and restructurings",
      "NCLT proceedings experience — insolvency and oppression matters",
    ],
    notableMatters: [
      {
        title: "Startup Shareholders' Dispute",
        outcome: "Settlement — equity restructured",
        description: "Advised a tech startup founder in a shareholder dispute, securing a favourable equity restructuring and exit terms.",
      },
      {
        title: "NCLT Insolvency Resolution",
        outcome: "Resolution plan approved",
        description: "Assisted in the preparation and filing of a resolution plan for a mid-size manufacturing company before the NCLT Hyderabad bench.",
      },
    ],
    metaTitle: "Adv. Suresh Kumar — Associate | Corporate Law | Sharma & Associates",
    metaDescription: "Profile of Adv. Suresh Kumar, Associate Advocate at Sharma & Associates, Hyderabad. Specialises in corporate law, company incorporation, and NCLT proceedings.",
  },
  {
    slug: "anitha-devi",
    initials: "AD",
    name: "Adv. Anitha Devi",
    designation: "Associate",
    enrollment: "Bar Council of Telangana · Enrl. No. TG/1567/2021",
    avatarBg: "#4B5563",
    specialisation: "Criminal Defence",
    practiceAreas: ["criminal-defence"],
    experience: "3 years",
    education: ["LL.B. — Hyderabad National Law School (2021)"],
    courts: ["Telangana High Court", "Sessions Courts — Hyderabad", "Metropolitan Magistrate Courts"],
    bio: "Adv. Anitha Devi joined the criminal defence practice at Sharma & Associates after completing her law degree and has developed quickly into a capable trial advocate. She handles bail applications, trial hearings, and criminal appeal matters under the close supervision of Adv. Ramarao. She is known for her diligent preparation and attention to procedural detail.",
    highlights: [
      "30+ bail applications filed — Sessions Court and High Court",
      "Regular appearance in Metropolitan Magistrate Courts, Hyderabad",
      "Specialised training in BNSS (new criminal procedure code)",
    ],
    notableMatters: [
      {
        title: "Bail in NDPS Matter",
        outcome: "Bail granted — Sessions Court",
        description: "Secured bail for a first-time accused in an NDPS matter by demonstrating lack of commercial quantity and personal use circumstances.",
      },
      {
        title: "FIR Quashing Petition",
        outcome: "FIR quashed — High Court",
        description: "Assisted in the preparation and hearing of a Section 528 BNSS petition, resulting in quashing of a false FIR filed in a civil dispute.",
      },
    ],
    metaTitle: "Adv. Anitha Devi — Associate | Criminal Defence | Sharma & Associates",
    metaDescription: "Profile of Adv. Anitha Devi, Associate Advocate at Sharma & Associates, Hyderabad. Specialises in criminal defence, bail applications, and trial advocacy.",
  },
];

export function getAttorneyBySlug(slug) {
  return attorneys.find((a) => a.slug === slug) ?? null;
}
